name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: Build executables
        run: go build -o blizzard-linux
      - name: Upload 
        uses: actions/upload-artifact@v4
        with:
          path: blizzard-linux
          name: blizzard-linux
      - name: Upload artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: blizzard-linux
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true
          tag: nightly
          bodyFile: "README.md"


  buildmac:

    runs-on: macos-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: Build executables
        run: go build -o blizzard-macos
      - name: Upload 
        uses: actions/upload-artifact@v4
        with:
          path: blizzard-macos
          name: blizzard-macos
      - name: Upload artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: blizzard-macos
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true
          tag: nightly
          bodyFile: "README.md"


  buildwin:

    runs-on: windows-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: Build executables
        run: go build -o blizzard-windows.exe
      - name: Upload 
        uses: actions/upload-artifact@v4
        with:
          path: blizzard-windows.exe
          name: blizzard-windows.exe
      - name: Upload artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: blizzard-windows.exe
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true
          tag: nightly
          bodyFile: "README.md"
